"""add vehicle status

Revision ID: 5985c5348534
Revises: 8f029286ad8a
Create Date: 2026-07-21 20:32:18.430701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5985c5348534'
down_revision: Union[str, Sequence[str], None] = '8f029286ad8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('ignition', sa.Boolean(), nullable=False),
    sa.Column('engine_running', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('OFFLINE', 'IDLE', 'MOVING', 'PARKED', name='vehicle_state_enum'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_vehicle_status_vehicle_id_vehicles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_status')),
    sa.UniqueConstraint('vehicle_id', name=op.f('uq_vehicle_status_vehicle_id'))
    )
    op.add_column('telemetry', sa.Column('battery_voltage', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('rpm', sa.Float(), nullable=True))
    op.add_column('telemetry', sa.Column('harsh_braking', sa.Boolean(), nullable=False))
    op.add_column('telemetry', sa.Column('harsh_acceleration', sa.Boolean(), nullable=False))
    op.add_column('telemetry', sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('telemetry', 'engine_rpm')
    op.drop_column('telemetry', 'gps_timestamp')
    op.drop_column('telemetry', 'altitude')
    op.drop_column('telemetry', 'heading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('heading', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('gps_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('engine_rpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('telemetry', 'recorded_at')
    op.drop_column('telemetry', 'harsh_acceleration')
    op.drop_column('telemetry', 'harsh_braking')
    op.drop_column('telemetry', 'rpm')
    op.drop_column('telemetry', 'battery_voltage')
    op.drop_table('vehicle_status')
    # ### end Alembic commands ###
