"""update telemetry schema

Revision ID: 7cde5d85bfd4
Revises: 5985c5348534
Create Date: 2026-07-24 07:13:43.293753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cde5d85bfd4'
down_revision: Union[str, Sequence[str], None] = '5985c5348534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    bind = op.get_bind()

    telemetry_state = sa.Enum(
        "OFFLINE",
        "IDLE",
        "MOVING",
        "PARKED",
        name="telemetry_state_enum",
    )

    telemetry_state.create(bind, checkfirst=True)

    op.add_column(
        "telemetry",
        sa.Column(
            "heading",
            sa.Float(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "ignition",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "engine_running",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "fuel",
            sa.Float(),
            nullable=False,
            server_default="100",
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "engine_temp",
            sa.Float(),
            nullable=False,
            server_default="85",
        ),
    )

    op.add_column(
        "telemetry",
        sa.Column(
            "state",
            telemetry_state,
            nullable=False,
            server_default="MOVING",
        ),
    )

    op.alter_column(
        "telemetry",
        "odometer",
        existing_type=sa.Float(),
        nullable=False,
    )

    op.create_index(
        op.f("ix_telemetry_vehicle_id"),
        "telemetry",
        ["vehicle_id"],
        unique=False,
    )

    op.drop_constraint(
        op.f("fk_telemetry_vehicle_id_vehicles"),
        "telemetry",
        type_="foreignkey",
    )

    op.drop_column("telemetry", "battery_voltage")
    op.drop_column("telemetry", "harsh_acceleration")
    op.drop_column("telemetry", "harsh_braking")
    op.drop_column("telemetry", "rpm")
    op.drop_column("telemetry", "ignition_on")
    op.drop_column("telemetry", "engine_temperature")
    op.drop_column("telemetry", "updated_at")
    op.drop_column("telemetry", "created_at")
    op.drop_column("telemetry", "fuel_level")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry', sa.Column('fuel_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('engine_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('ignition_on', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('rpm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('telemetry', sa.Column('harsh_braking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('harsh_acceleration', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('telemetry', sa.Column('battery_voltage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_telemetry_vehicle_id_vehicles'), 'telemetry', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_telemetry_vehicle_id'), table_name='telemetry')
    op.alter_column('telemetry', 'odometer',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('telemetry', 'state')
    op.drop_column('telemetry', 'engine_temp')
    op.drop_column('telemetry', 'fuel')
    op.drop_column('telemetry', 'engine_running')
    op.drop_column('telemetry', 'ignition')
    op.drop_column('telemetry', 'heading')
    # ### end Alembic commands ###
